### PR TITLE
update for scala3

### PR DESCRIPTION
**Pull request by mpollmeier**

### CODE REVIEW

**Review by fabsx00 — APPROVED** [review]

**Comment by mpollmeier** [comment]
@ursachec any idea what those build failures are all about?

e.g. 
```
(undefined) ./node_modules/eta/dist/eta.module.mjs 549:62-74
./node_modules/eta/dist/eta.module.mjs
Can't import the named export 'dirname' from non EcmaScript module (only default export is available)
 @ ./node_modules/@docusaurus/core/lib/client/serverEntry.js
(undefined) ./node_modules/eta/dist/eta.module.mjs 610:13-23
Can't import the named export 'existsSync' from non EcmaScript module (only default export is available)
 @ ./node_modules/@docusaurus/core/lib/client/serverEntry.js
(undefined) ./node_modules/eta/dist/eta.module.mjs 619:10-20
Can't import the named export 'existsSync' from non EcmaScript module (only default export is available)
 @ ./node_modules/@docusaurus/core/lib/client/serverEntry.js
(undefined) ./node_modules/eta/dist/eta.module.mjs 648:10-20
Can't import the named export 'existsSync' from non EcmaScript module (only default export is available)
 @ ./node_modules/@docusaurus/core/lib/client/serverEntry.js
(undefined) ./node_modules/eta/dist/eta.module.mjs 552:7-19
Can't import the named export 'extname' from non EcmaScript module (only default export is available)
 @ ./node_modules/@docusaurus/core/lib/client/serverEntry.js
(undefined) ./node_modules/eta/dist/eta.module.mjs 672:11-23
Can't import the named export 'readFileSync' from non EcmaScript module (only default export is available)
 @ ./node_modules/@docusaurus/core/lib/client/serverEntry.js
(undefined) ./node_modules/eta/dist/eta.module.mjs 549:22-34
Can't import the named export 'resolve' from non EcmaScript module (only default export is available)
 @ ./node_modules/@docusaurus/core/lib/client/serverEntry.js
error building locale=en
Error: Failed to compile with errors.
    at /home/runner/work/website/website/docs.joern.io/node_modules/@docusaurus/core/lib/webpack/utils.js:181:24
```

**Comment by ursachec** [comment]
Unfortunately no @mpollmeier, I'd have to spend some time looking into it. From what I can tell, the reason for these appearing in the first place is Node 12 reaching end-of-life and GitHub replacing Actions using Node 12 with Node 16 under the hood https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/. I've seen these build errors some time again also, and tried a few quick fixes, but none worked and I didn't remember to come back to the issue again. What's required is bumping Docusaurus together with Node. I'll try again some time this week and see if I manage to get the build to green again

**Comment by mpollmeier** [comment]
@ursachec did you have any luck yet or should I move this part of the docs to a readme / markdown in the repo for now?

**Comment by ursachec** [comment]
@mpollmeier Didn't manage to look into it yet, no, sorry, got sidetracked by other tasks. Yes, a readme/markdown in the repo sounds like a good temporary alternative

**Comment by ursachec** [comment]
@mpollmeier I have an initial version of a new documentation website up at https://github.com/joernio/website/pull/82. I think it should do well as a replacement. @fabsx00 can you take care of the deployment?

**Comment by ursachec** [comment]
@mpollmeier i brought in the scala3 changes via this PR https://github.com/joernio/website/pull/84. closing this one

**Pull request closed without merging**
